package es.ilerna.drivetest

import android.content.Context
import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.lifecycle.lifecycleScope
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.database.ktx.database
import com.google.firebase.ktx.Firebase
import es.ilerna.drivetest.application.App
import es.ilerna.drivetest.database.entities.Explicacion
import es.ilerna.drivetest.database.entities.Preguntas
import es.ilerna.drivetest.database.entities.Respuestas
import es.ilerna.drivetest.databinding.ActivityHomeBinding
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext


class HomeActivity : AppCompatActivity() {

    private lateinit var binding:ActivityHomeBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityHomeBinding.inflate(layoutInflater)
        setContentView(binding.root)

        //Ponemos en nuestro editText el email introducido en la pantalla de login
        val bundle = intent.extras
        val email = bundle?.getString("email")
        binding.tvEmail.text = email

        //Recupero el nombre del usuario de la base de datos y muestro el saludo en pantalla
        val database = Firebase.database.reference
        val usuario = FirebaseAuth.getInstance().currentUser!!.uid
        database.child(usuario).child("Nombre").get().addOnSuccessListener {
        binding.tvHola.text= "Hola ${it.value}!"}
        logout()

        //Guardado de datos con SharedPreferences
        val prefs = getSharedPreferences(getString(R.string.prefs_file), Context.MODE_PRIVATE).edit()
        prefs.putString("email", email)
        prefs.apply()

        //Cargamos la base de datos
        //Esta funcion la utilizo solamente para crear la base de datos, una vez creada la exporto
        //en un fichero Database.db incluido en el directorio assets, y desde ahi la cargo
        //siempre que se ejecute la app

        //creaBaseDeDatos()

        //Depende de la opcion seleccionada abrimos sus respectivos activities
        binding.btnTest.setOnClickListener{opcionTest(email)}

        binding.btnEstadisticas.setOnClickListener{opcionEstadisticas(email)}

        binding.btnAcerca.setOnClickListener{opcionAcercaDe(email)}

        binding.btnAyuda.setOnClickListener{opcionAyuda(email)}

        binding.btnSalir.setOnClickListener { finishAffinity()}
    }

    private fun logout(){

        title = "Inicio"

        binding.btnLogout.setOnClickListener{
            val prefs = getSharedPreferences(getString(R.string.prefs_file), Context.MODE_PRIVATE).edit()
            prefs.clear()
            prefs.apply()

            FirebaseAuth.getInstance().signOut()
            val logIntent = Intent(this, LogActivity::class .java)
            startActivity(logIntent)
        }
    }

    private fun opcionEstadisticas(email: String?){
        val estadisticasIntent = Intent(this, EstadisticasActivity::class.java).apply {
            putExtra("email", email)
        }
        startActivity(estadisticasIntent)
    }

    private fun opcionTest(email: String?) {
        val tiposIntent = Intent(this, TiposActivity::class.java).apply {
            putExtra("email", email)
        }
        startActivity(tiposIntent)
    }

    private fun opcionAcercaDe(email: String?){
        val acercadeIntent = Intent(this, AcercaActivity::class.java).apply {
            putExtra("email", email)
        }
        startActivity(acercadeIntent)
    }

    private fun opcionAyuda(email: String?){
        val ayudaIntent = Intent(this, AyudaActivity::class.java).apply {
            putExtra("email", email)
        }
        startActivity(ayudaIntent)
    }
    private fun creaBaseDeDatos() {         //Inserto las preguntas y respuestas en sus respectivas tablas
        lifecycleScope.launch {
            withContext(Dispatchers.IO) {

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Es una vía interurbana de doble sentido y tres carriles separados por líneas discontinuas, " +
                        "¿dónde se situará el conductor de un turismo para cambiar de dirección a la izquierda?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En el carril situado a la izquierda de la calzada", esCorrecta = false, preguntaId = 1))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En el carril de su derecha, como norma general", esCorrecta = false, preguntaId = 1))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En el carril central", esCorrecta = true, preguntaId = 1))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En vías de tres carriles y doble sentido de circulación, el carril centrar servirá para realizar adelantamiento y cambios de dirección a la izquierda.", preguntaId = 1))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En caso de sufrir un reventón circulando por una vía a velocidad elevada, ¿es aconsejable pisar el freno con brusquedad?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, el frenado debe ser suave y progresivo", esCorrecta = true, preguntaId = 2))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, para mantener con mayor facilidad la trayectoria recta del vehículo", esCorrecta = false, preguntaId = 2))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Solo si el reventón se produce en una de las ruedas delanteras", esCorrecta = false, preguntaId = 2))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En ningún caso deberemos frenar bruscamente o realizar maniobras bruscas.", preguntaId = 2))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los cinturones de seguridad y los airbags son sistemas de..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Seguridad activa", esCorrecta = false, preguntaId = 3))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Seguridad pasiva", esCorrecta = true, preguntaId = 3))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Conducción eficiente", esCorrecta = false, preguntaId = 3))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Permiten que se minimicen los daños en el conductor y en los ocupantes ante un accidente.", preguntaId = 3))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cómo debe colocar el navegador GPS portátil en el vehiculo?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Justo detrás del volante, a la altura de los ojos del conductor", esCorrecta = false, preguntaId = 4))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Debajo del volante, tan cerca del suelo como sea posible", esCorrecta = false, preguntaId = 4))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Donde no entorpezca ni la visión ni el despliegue del airbag", esCorrecta = true, preguntaId = 4))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El navegador debe colocarse, según los fabricantes, abajo, lo más pegado al salpicadero, a derecha o a izquierda, para poder consultarlo de un simple vistazo. ¡Nunca en el centro!", preguntaId = 4))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Qué alumbrado llevará encendido una motocicleta durante el día?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El de corto alcance o cruce", esCorrecta = true, preguntaId = 5))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El de posición o el de corto alcance", esCorrecta = false, preguntaId = 5))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Ninguno", esCorrecta = false, preguntaId = 5))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las motocicletas que circulen durante el día por cualquier vía pública, tanto urbana como interurbana, deberán llevar encendida la luz de cruce independientemente de las condiciones de visibilidad.", preguntaId = 5))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Puede realizar un cambio de sentido en un lugar donde esté prohibido adelantar?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, excepto entre la puesta y la salida de sol, porque disminuye la visibilidad", esCorrecta = false, preguntaId = 6))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, salvo que el cambio de sentido esté expresamente autorizado", esCorrecta = true, preguntaId = 6))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, cuando la circulación en sentido contrario lo permita", esCorrecta = false, preguntaId = 6))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Realizar un cambio de sentido está prohibido en toda situación que impida comprobar que no vamos a poner en peligro u obstaculizar a otros usuarios de la vía, como por ejemplo en curvas y cambios de rasante de visibilidad reducida o en el caso de niebla o lluvia intensa.", preguntaId = 6))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En un vehículo de autoescuela realizando clases prácticas, ¿quién es considerado el conductor?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Tanto al alumno como al profesor", esCorrecta = false, preguntaId = 7))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El alumno, ya que maneja el volante", esCorrecta = false, preguntaId = 7))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El profesor, por ser responsable de los mandos adicionales", esCorrecta = true, preguntaId = 7))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En un vehículo de autoescuela se considera que el conductor no es la persona que maneja la dirección, en este caso el alumno, sino el profesor responsable de los mandos adicionales.", preguntaId = 7))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Dónde está permitido que viaje un niño que no alcance los 135 centímetros de estatura?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En cualquiera de los asientos traseros utilizando el cinturón para adultos", esCorrecta = false, preguntaId = 8))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En un asiento delantero o trasero, utilizando siempre el cinturón de seguridad para adultos", esCorrecta = false, preguntaId = 8))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En el asiento trasero, utilizando siempre un dispositivo de retención homologado en función de su talla y peso", esCorrecta = true, preguntaId = 8))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Cuando la estatura de los menores sea superior a 1,35 m, podrán ocupar el asiento delantero utilizando el cinturón de seguridad para adultos.", preguntaId = 8))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Una línea blanca contínua sobre la calzada, sensiblemente más ancha que en el caso general..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Indica la existencia de un carril especial", esCorrecta = true, preguntaId = 9))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sirve para delimitar, únicamente, los carriles bus", esCorrecta = false, preguntaId = 9))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Indica el borde de la calzada", esCorrecta = false, preguntaId = 9))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "No sólo los carriles bus son carriles especiales, también existen carriles especiales de entrada o salida.", preguntaId = 9))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El seguro obligatorio, ¿cubre los daños en la persona del conductor del vehículo asegurado?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, en todo caso", esCorrecta = false, preguntaId = 10))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, salvo cuando el conductor es el tomador del seguro", esCorrecta = false, preguntaId = 10))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 10))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El seguro obligatorio cubre, hasta una cuantía limitada, la responsabilidad civil del conductor del vehículo cuando se producen daños, tanto corporales como materiales, por hechos de la circulación.", preguntaId = 10))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La mayor parte de las víctimas mortales por accidente de circulación se producen en..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Vías interurbanas", esCorrecta = true, preguntaId = 11))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Vías urbanas", esCorrecta = false, preguntaId = 11))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Travesías", esCorrecta = false, preguntaId = 11))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La mayoría de las víctimas, especialmente las mortales, se producen en los accidentes en vías interurbanas, en los tramos rectos más que en las curvas.", preguntaId = 11))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuántos espejos retrovisores tienen que llevar instalados las motocicletas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Obligatoriamente uno en el lado derecho, pero pueden llevar dos", esCorrecta = false, preguntaId = 12))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Siempre deben llevar dos espejos, uno en cada lado", esCorrecta = false, preguntaId = 12))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Un espejo exterior izquierdo si no superan los 100 km/h y dos, uno en cada lado, si la velocidad es mayor.", esCorrecta = true, preguntaId = 12))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las motocicletas con o sin sidecar, cuya velocidad máxima no supere los 100 Km/h, llevarán un espejo retrovisor exterior izquierdo (pudiendo llevar opcionalmente otro en el lado derecho) y, si supera esa velocidad, llevarán uno a cada lado.", preguntaId = 12))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Está permitida la circulación de animales por una carretera convencional?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, únicamente cuando no exista vía pecuaria", esCorrecta = true, preguntaId = 13))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 13))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, excepto cuando circulen en rebaño", esCorrecta = false, preguntaId = 13))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los animales solamente podrán circular por las carreteras convencionales cuando no exista ninguna otra vía especialmente adaptada para ellos.", preguntaId = 13))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Qué aportan a la seguridad vial los sistemas avanzados de ayuda a la conducción también conocidos como ADAS?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Disminuyen el tiempo de reacción del conductor", esCorrecta = false, preguntaId = 14))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Permiten al conductor reducir su nivel de alerta", esCorrecta = false, preguntaId = 14))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Mejoran notablemente la seguridad activa del vehículo", esCorrecta = true, preguntaId = 14))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los sistemas ADAS (Advanced Driver Assistance Systems) son un conjunto de sistemas instalados en el vehículo que prestan asistencia al conductor para aumentar la seguridad y facilitar la conducción.", preguntaId = 14))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuál es la tasa de alcohol máxima permitida a un conductor novel?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,25 miligramos de alcohol por litro de aire espirado", esCorrecta = false, preguntaId = 15))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,3 miligramos de alcohol por litro de aire espirado", esCorrecta = false, preguntaId = 15))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,15 miligramos de alcohol por litro de aire espirado", esCorrecta = true, preguntaId = 15))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los conductores noveles, durante los 2 primeros años de su primer permiso, no podrán superar los 0,3 g/l en sangre o 0,15 mg/l en aire espirado.", preguntaId = 15))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Cuando un vehículo accidentado comienza a arder, ¿qué se debe hacer primero?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Apagar el fuego", esCorrecta = false, preguntaId = 16))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sacar rápidamente a los heridos", esCorrecta = true, preguntaId = 16))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Ir a buscar ayuda", esCorrecta = false, preguntaId = 16))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Se debe prestar a los heridos el auxilio que resulte más adecuado para que no resulte más agravada su situación.", preguntaId = 16))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Está permitido colocar el dispositivo de preseñalización de peligro alejado del vehículo averiado?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, alejado se podrá apreciar mejor.", esCorrecta = false, preguntaId = 17))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, debe estar al menos a 100 metros", esCorrecta = false, preguntaId = 17))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, se debe colocar en la parte más alta posible del vehículo inmovilizado", esCorrecta = true, preguntaId = 17))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El dispositivo de preseñalización de peligro es un dispositivo de color amarillo auto y de alimentación autónoma que se colocará en la parte más alta del vehículo inmovilizado garantizando su máxima visibilidad.", preguntaId = 17))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Para entrar en una autopista, ¿a qué velocidad debe circular?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A la máxima velocidad permitida en la autopista", esCorrecta = false, preguntaId = 18))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Siempre muy despacio para entrar con seguridad", esCorrecta = false, preguntaId = 18))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A la velocidad adecuada que permita incorporarse con seguridad", esCorrecta = true, preguntaId = 18))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El conductor que se incorpore a una autopista procurará hacerlo con la velocidad adecuada a la vía, teniendo en cuenta la posición, trayectoria y velocidad de los usuarios que transiten por ella, incluso deteniéndose, en caso de ser necesario.", preguntaId = 18))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Qué es una detención?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "La inmovilización del vehículo por necesidades de la circulación", esCorrecta = true, preguntaId = 19))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Una parada por cualquier causa", esCorrecta = false, preguntaId = 19))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Un estacionamiento sin bajarse del vehículo", esCorrecta = false, preguntaId = 19))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La detención es la inmovilización accidental o momentánea de un vehículo por una emergencia, por necesidades de la circulación o para cumplir algún precepto reglamentario.", preguntaId = 19))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Tiene alguna obligación cuando su vehículo va a ser adelantado?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, señalizar con el intermitente derecho para indicar que puede realizar la maniobra con seguridad", esCorrecta = false, preguntaId = 20))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, la responsabilidad es del vehículo que adelanta", esCorrecta = false, preguntaId = 20))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, ceñirse al borde derecho de la calzada para facilitar la maniobra", esCorrecta = true, preguntaId = 20))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El conductor del vehículo que va a ser adelantado estará obligado a disminuir la velocidad de su vehículo cuando se produzca alguna situación que entrañe peligro.", preguntaId = 20))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Para hacer frente al covid19..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Los trabajadores de los servicios de transporte que tengan contacto directo con los viajeros deberán ir provistos de mascarillas y tener acceso a soluciones hidroalcohólicas para practicar una higiene de manos frecuente", esCorrecta = false, preguntaId = 21))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El uso de mascarillas que cubran nariz y boca será obligatorio para todos los usuarios del transporte en autobús", esCorrecta = false, preguntaId = 21))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A Y B son correctas", esCorrecta = true, preguntaId = 21))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Desde el 4 de mayo de 2020, el uso de mascarilla que cubra la nariz y la boca es obligatorio para viajar en autobús. Desde entonces han de llevarla tanto los usuarios como los conductores.", preguntaId = 21))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El funcionamiento del airbag, ¿puede llegar a ser peligroso en un accidente?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, siempre", esCorrecta = false, preguntaId = 22))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, si no se lleva puesto el cinturón de seguridad", esCorrecta = true, preguntaId = 22))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 22))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Es un complemento del cinturón de seguridad, por lo que siempre se utilizarán conjuntamente.", preguntaId = 22))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuál debe ser su comportamiento al ceder el paso?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse en las intersecciones si se acerca otro vehículo", esCorrecta = false, preguntaId = 23))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Parar y comprobar si otro usuario de la vía tiene prioridad", esCorrecta = false, preguntaId = 23))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No obligar al vehículo que tiene prioridad a modificar bruscamente su trayectoria o velocidad", esCorrecta = true, preguntaId = 23))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Debemos mostrar, de forma clara, nuestra intención de respetar la prioridad de paso en la próxima intersección a los vehículos que circulen por la vía a la que nos aproximamos o al carril al que pretendemos incorporarnos.", preguntaId = 23))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La fatiga, ¿provoca lentitud y falta de precisión en los movimientos?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, la fatiga sólo produce calambres", esCorrecta = false, preguntaId = 24))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 24))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, por lo cual la conducción se hace más peligrosa", esCorrecta = true, preguntaId = 24))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La fatiga supone un descenso en la capacidad de rendimiento del conductor, es decir, en la capacidad para conducir con los niveles normales de seguridad.", preguntaId = 24))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La tasa máxima de alcoholemia permitida en sangre para conductores profesionales es..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,30 gramos por litro", esCorrecta = true, preguntaId = 25))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,30 miligramos por litro.", esCorrecta = false, preguntaId = 25))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "0,50 gramos por litro", esCorrecta = false, preguntaId = 25))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Esto es para conductores de vehículos destinados al transporte de mercancías con masa máxima autorizada superior a 3.500 Kg., los destinados al transporte de viajeros de más de nueve plazas y de servicio público.", preguntaId = 25))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los accidentes de tráfico generan..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Un enorme impacto económico, solamente", esCorrecta = false, preguntaId = 26))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Daños materiales y costes sanitarios, administrativos y humanos", esCorrecta = true, preguntaId = 26))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Daños materiales y costes humanos, únicamente", esCorrecta = false, preguntaId = 26))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los accidentes de tráfico no solo generan daños materiales y situaciones humanas dramáticas, también generan un alto coste económico debido a las gestiones sanitarias, administrativas,etc.", preguntaId = 26))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El efecto submarino se produce cuando..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El apoyacabezas está mal regulado", esCorrecta = false, preguntaId = 27))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El cinturón de seguridad no es capaz de retener adecuadamente durante un accidente y el cuerpo se desliza por debajo de él", esCorrecta = true, preguntaId = 27))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "la distancia con el airbag es incorrecta", esCorrecta = false, preguntaId = 27))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Un asiento demasiado inclinado, utilizar cojín o fundas en los asientos no adecuadas, puede producir que nos deslicemos por debajo del cinturón (efecto submarino).", preguntaId = 27))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Al auxiliar a una víctima de un accidente de tráfico, ¿debe darle alimentos o bebidas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, si lo piden", esCorrecta = false, preguntaId = 28))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 28))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Alimentos no, pero bebidas sí", esCorrecta = false, preguntaId = 28))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Como norma general no se debe dar alimentos o bebidas a los heridos, y en ningún caso bebidas alcohólicas.", preguntaId = 28))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Fuera de poblado, ¿qué separación lateral debe dejar una motocicleta al adelantar un camión?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Una distancia proporcional a la velocidad a la que circule", esCorrecta = false, preguntaId = 29))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Un espacio no inferior a 1,50 metros", esCorrecta = true, preguntaId = 29))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Una separación que considere segura en función de las circunstancias del momento", esCorrecta = false, preguntaId = 29))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "También respetará este margen con peatones, animales y vehículos de tracción animal. De igual manera el resto de vehículos deberán de dejar ese espacio lateral al adelantar a vehículos de dos ruedas", preguntaId = 29))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿El pasajero de una moto debe llevar abrochado el casco?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, y además el conductor es responsable de que lo lleve abrochado", esCorrecta = true, preguntaId = 30))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, siendo el pasajero el único responsable", esCorrecta = false, preguntaId = 30))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No es obligatorio, pero si aconsejable", esCorrecta = false, preguntaId = 30))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En este caso es responsabilidad del conductor que el pasajero lleve el casco correctamente abrochado.", preguntaId = 30))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Siempre que el recorrido hacia atrás no supere los 15 metros ni invada un cruce de vías, podrá circular marcha atrás..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Como maniobra complementaria de la parada", esCorrecta = true, preguntaId = 31))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En autovías y autopistas que discurran por poblado", esCorrecta = false, preguntaId = 31))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando no sea posible cambiar de dirección o sentido de la marcha", esCorrecta = false, preguntaId = 31))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Se puede circular marcha atrás para hacer una parada, para realizar un estacionamiento o incluso para incorporarse a la circulación", preguntaId = 31))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Salvo que exista señal que lo prohíba, por los arcenes de las autovías se permite circular..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A conductores de bicicletas mayores de 14 años", esCorrecta = true, preguntaId = 32))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A peatones", esCorrecta = false, preguntaId = 32))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A vehículos de tracción animal", esCorrecta = false, preguntaId = 32))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los conductores mayores de 14 años pueden circular por los arcenes de las autovías, salvo que una señal lo prohíba por razones justificadas de seguridad vial, en cuyo caso, un panel indicará un itinerario alternativo.", preguntaId = 32))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Si un vehículo de la policía de tráfico se sitúa detrás de usted y enciende un dispositivo con una luz amarilla intermitente hacia delante, ¿que debe hacer?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse en el lado izquierdo de la calzada, delante del vehículo", esCorrecta = false, preguntaId = 33))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse y, en su caso, seguir las instrucciones del agente", esCorrecta = true, preguntaId = 33))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Reducir la velocidad y apartarse a la derecha, para facilitar el adelantamiento", esCorrecta = false, preguntaId = 33))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Cuando el que se sitúa detrás de nuestro vehículo es un coche de policía y además activa un dispositivo de emisión de luz roja o amarilla hacia delante de forma intermitente o destellante, entonces el conductor debe detenerse en el lado derecho.", preguntaId = 33))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un estado psicofísico inadecuado puede aumentar el tiempo de reacción, como si conducimos..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Usando gafas graduadas", esCorrecta = false, preguntaId = 34))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Después de una comida ligera", esCorrecta = false, preguntaId = 34))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Después de una fuerte discusión", esCorrecta = true, preguntaId = 34))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Toda alteración en nuestro sistema tanto físico como psíquico afectará a nuestra conducción", preguntaId = 34))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Si circula por una vía interurbana insuficientemente iluminada a una velocidad inferior a 40km/h, ¿Qué luces deberá llevar encendidas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Las luces de corto alcance, al menos", esCorrecta = true, preguntaId = 35))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Las luces de largo alcance", esCorrecta = false, preguntaId = 35))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Las luces de posición solamente", esCorrecta = false, preguntaId = 35))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Es obligatorio sustituir la luz de carretera por la de cruce si deslumbramos.", preguntaId = 35))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Al estacionar un vehículo en pendiente ascendente, su conductor deberá"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Apoyar una rueda delantera en el bordillo y orientarla hacia fuera de la calzada", esCorrecta = false, preguntaId = 36))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Dejar accionado el freno de estacionamiento", esCorrecta = true, preguntaId = 36))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Dejar seleccionada la marcha atrás", esCorrecta = false, preguntaId = 36))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Al estacionar en una pendiente se debe dejar puesto el freno de estacionamiento y dejar colocada la primera marcha si la pendiente es ascendente y la marcha atrás si es descendente.", preguntaId = 36))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El alcohol puede detectarse en la sangre a partir de los 5 minutos de haberlo consumido, pero ¿Cuándo alcanza su máximo nivel (pico de alcoholemia)?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Entre los 30 y los 90 minutos después de haberlo consumido", esCorrecta = true, preguntaId = 37))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Entre los 120 y los 130 minutos después de haberlo consumido", esCorrecta = false, preguntaId = 37))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Entre las tres y las cuatro horas después de haberlo consumido", esCorrecta = false, preguntaId = 37))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El alcohol puede empezar a detectarse en la sangre a los 5 minutos de haberlo ingerido y alcanza su máximo nivel entre los 30 y 90 minutos siguientes.", preguntaId = 37))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Respecto al uso del cinturón de seguridad, como norma general, el ocupante de un turismo distinto del conductor está obligado a..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "LLevarlo puesto y correctamente abrochado", esCorrecta = true, preguntaId = 38))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Llevarlo puesto y sin abrochar, si viaja en la plaza delantera", esCorrecta = false, preguntaId = 38))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Llevarlo puesto y abrochado solo en vías interurbanas", esCorrecta = false, preguntaId = 38))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Todos los ocupantes distintos del conductor que circulen dentro de un vehículo, estarán obligados a llevar puesto y correctamente abrochado el cinturón de seguridad como sistema de seguridad pasiva.", preguntaId = 38))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Buscar una emisora de radio o manipular el reproductor de música, ¿Pueden distraer al conductor?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Solo si las emisoras de radio no están guardadas en memoria", esCorrecta = false, preguntaId = 39))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 39))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, aumentando el riesgo de accidente", esCorrecta = true, preguntaId = 39))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Consultar o manipular el GPS, la radio o el climatizador puede suponer una distracción al volante para el conductor al retirar la vista de la calzada aunque sea por unos segundos.", preguntaId = 39))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuál es el número máximo de plazas autorizadas, incluída la del conductor, que puede tener una furgoneta para poder circular?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "9 plazas", esCorrecta = true, preguntaId = 40))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "3 plazas", esCorrecta = false, preguntaId = 40))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "5 plazas", esCorrecta = false, preguntaId = 40))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El permiso de conducir de la clase B, permitirá conducir vehículos siempre que no superen los 3500 kilogramos y máximo 9 plazas incluido el conductor.", preguntaId = 40))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Circulando con lluvia muy intensa, ¿es correcto encender la luz antiniebla trasera?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 41))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, sólo puede utilizarse con niebla densa o fuerte nevada", esCorrecta = false, preguntaId = 41))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, pero su uso es opcional", esCorrecta = false, preguntaId = 41))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El alumbrado antiniebla trasero, durante el día, se usará como mínimo conjuntamente con el antiniebla delantero o el de corto alcance. De noche, como mínimo con el de corto alcance.", preguntaId = 41))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Para que pueda circular un ciclomotor, ¿es obligatorio que esté asegurado?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, pero solamente los que tienen más de dos ruedas", esCorrecta = false, preguntaId = 42))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 42))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 42))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El propietario de un vehículo de motor, incluidos los ciclomotores, tiene la obligación de suscribir un seguro de responsabilidad civil, popularmente conocido como \"seguro obligatorio\".", preguntaId = 42))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los conductores jóvenes suelen tener más accidentes..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Porque se distraen con mayor facilidad", esCorrecta = false, preguntaId = 43))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por un comportamiento exhibicionista cuando van en grupo", esCorrecta = true, preguntaId = 43))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por su desconocimiento de las normas", esCorrecta = false, preguntaId = 43))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los accidentes de tráfico en España en 2017 se cobraron la vida de 1.200 personas, lo que supone más de 3 fallecimientos al día, muchos de ellos jóvenes.", preguntaId = 43))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La vía, su entorno y el propio vehículo, ¿pueden favorecer la aparición de distracciones al volante?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, el vehículo y la vía pero no su entorno", esCorrecta = false, preguntaId = 44))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, la vía pero no su entorno", esCorrecta = false, preguntaId = 44))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 44))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las distracciones pueden ser producidas tanto por sucesos en la vía como en su entorno o en el propio vehículo. Las distracciones son responsables de casi el 40% de los accidentes.", preguntaId = 44))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Pueden llevar las motocicletas la luz antiniebla delantera?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, todas las motocicletas, con o sin sidecar.", esCorrecta = true, preguntaId = 45))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, pero sólo las motocicletas con sidecar.", esCorrecta = false, preguntaId = 45))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, las motocicletas no pueden llevar luces antiniebla.", esCorrecta = false, preguntaId = 45))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La luz antiniebla delantera, no es obligatoria en ningún tipo de vehículo, pero pueden disponer de ella todos los vehículos de motor. No pueden llevarla los motocultores ni los ciclomotores.", preguntaId = 45))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un vehículo expulsa más humo del permitido, ¿puede seguir circulando?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, porque el humo no es nocivo ni contamina.", esCorrecta = false, preguntaId = 46))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 46))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, siempre que circule fuera de poblado.", esCorrecta = false, preguntaId = 46))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Está prohibida la emisión de perturbaciones electromagnéticas, ruidos, gases, humos y otros contaminantes por encima de las limitaciones establecidas.", preguntaId = 46))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La distancia de detención puede variar en función..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Del mal estado del vehículo, del conductor o de la vía", esCorrecta = true, preguntaId = 47))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Del mal estado de la vía únicamente", esCorrecta = false, preguntaId = 47))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Del mal estado del vehículo solamente", esCorrecta = false, preguntaId = 47))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La distancia de detención es la distancia que recorre el vehículo desde que se percibe un obstáculo o peligro hasta que se detiene por completo el vehículo. Es decir la suma de la distancia de reacción y la distancia de frenado.", preguntaId = 47))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Ante un paso a nivel cuyas barreras están en movimiento, ¿es obligatorio detenerse?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, pero solamente cuando el vehículo no pueda pasar por debajo", esCorrecta = false, preguntaId = 48))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, puesto que no se encuentran en posición horizontal", esCorrecta = false, preguntaId = 48))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 48))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Queda prohibido entrar en un paso a nivel o puente móvil cuyas barreras o semibarreras estén atravesadas o en movimiento, o cuando sus semáforos impidan el paso.", preguntaId = 48))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Está permitido que un vehículo circule sin silenciador de explosiones?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, cuando no moleste a otros usuarios de la vía", esCorrecta = false, preguntaId = 49))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, excepto los ciclomotores de dos ruedas", esCorrecta = false, preguntaId = 49))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 49))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Al circular por las vías públicas los vehículos no pueden producir ruidos que superen los niveles máximos permitidos, como en el caso de circular con el escape libre o el silenciador roto.", preguntaId = 49))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los ciclomotores de dos ruedas deben llevar..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Dos espejos retrovisores exteriores obligatorios, uno al lado izquierdo y otro al lado derecho", esCorrecta = false, preguntaId = 50))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Es obligatorio el del lado izquierdo y optativo el del lado derecho", esCorrecta = true, preguntaId = 50))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Es optativo el del lado izquierdo y obligatorio el del lado derecho", esCorrecta = false, preguntaId = 50))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los ciclomotores llevarán obligatoriamente un espejo retrovisor en el lado izquierdo siendo optativo el lado derecho.", preguntaId = 50))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuál es la velocidad máxima genérica para un turismo en autovía?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "90 km/h", esCorrecta = false, preguntaId = 51))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "100 km/h", esCorrecta = false, preguntaId = 51))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "120 km/h", esCorrecta = true, preguntaId = 51))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La velocidad máxima genérica en autopista y autovía es de 120 km/h para turismos, motocicletas, autocaravanas de MMA igual o inferior a 3500 kg y pick-ups.", preguntaId = 51))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuándo debe comprobar el reglaje de los espejos retrovisores?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Antes de iniciar la marcha en terreno llano y recto", esCorrecta = true, preguntaId = 52))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando el vehículo circule en terreno llano y recto", esCorrecta = false, preguntaId = 52))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Circulando a una velocidad lenta", esCorrecta = false, preguntaId = 52))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los espejos retrovisores se deben de regular en terreno llano y recto, con el vehículo parado y antes de emprender la marcha.", preguntaId = 52))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El conductor está obligado a advertir mediante señales ópticas..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sólo las maniobras que no impliquen un desplazamiento lateral", esCorrecta = false, preguntaId = 53))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El propósito de inmovilizar su vehículo o frenar su marcha de modo considerable", esCorrecta = true, preguntaId = 53))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Únicamente el propósito de frenar su vehículo", esCorrecta = false, preguntaId = 53))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Esto lo haremos mediante el empleo reiterado de las luces de frenado o moviendo el brazo alternativamente de arriba abajo, con movimientos cortos y rápidos.", preguntaId = 53))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Circulando observa que se aproxima una ambulancia en servicio urgente. Debe tener en cuenta que..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Debe facilitarle el paso apartándose a la derecha o deteniéndose si fuera preciso", esCorrecta = true, preguntaId = 54))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Puede saltarse algún semáforo para dejar pasar a la ambulancia", esCorrecta = false, preguntaId = 54))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Deberá circular a mayor velocidad para abrirle paso", esCorrecta = false, preguntaId = 54))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Se deben de adoptar las medidas adecuadas para facilitar el paso de los vehículos en servicio urgente dependiendo de las circunstancias del momento y lugar.", preguntaId = 54))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Puede circular con su motocicleta por un carril bus?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, con carácter general", esCorrecta = true, preguntaId = 55))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, pero sólo para adelantar y durante el recorrido indispensable", esCorrecta = false, preguntaId = 55))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, en caso de circulación muy densa", esCorrecta = false, preguntaId = 55))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El carril bus indica la prohibición a los conductores de los vehículos que no sean de transporte colectivo de circular por el carril indicado. La mención \"taxi\" autoriza también a los taxis la utilización de este carril.", preguntaId = 55))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los vehículos que incorporan LED de última generación, ¿cómo pueden evitar el deslumbramiento a otros usuarios de la vía entre la puesta y la salida del sol?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Desviando las luces hacia la derecha mientras haya en la vía otros usuarios que puedan ser deslumbrados", esCorrecta = false, preguntaId = 56))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Reduciendo la velocidad del vehículo llegando incluso a detenerlo", esCorrecta = false, preguntaId = 56))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Reduciendo la intensidad de la luz que incide directamente sobre el objetivo, permitiendo al conductor gozar de la máxima visibilidad del resto de la carretera", esCorrecta = true, preguntaId = 56))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La tecnología LED evita que los demás conductores puedan ser deslumbrados, ya que, este sistema puede desconectar varios LED para evitar esto y solo con este tipo de iluminación puede llevarse a cabo.", preguntaId = 56))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La carga transportada en un vehículo, debe estar dispuesta de forma que..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No oculte los dispositivos de alumbrado o de señalización luminosa", esCorrecta = true, preguntaId = 57))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Ocupe el mínimo espacio posible", esCorrecta = false, preguntaId = 57))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No oculte los dispositivos de alumbrado, aunque puede ocultar la señalización luminosa", esCorrecta = false, preguntaId = 57))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La carga y los accesorios que se utilicen para su acondicionamiento o protección, estarán dispuestos de tal manera que no oculten los dispositivos de alumbrado o de señalización luminosa ni las advertencias manuales de los conductores.", preguntaId = 57))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En una vía urbana de sentido único, si los carriles no están delimitados por marcas viales, ¿por dónde está obligado a circular el conductor de un turismo?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por el carril que mejor convenga a su destino", esCorrecta = false, preguntaId = 58))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por el centro de la calzada", esCorrecta = false, preguntaId = 58))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por el carril derecho, pudiendo utilizar el resto cuando las circunstancias lo aconsejen", esCorrecta = true, preguntaId = 58))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En el caso de circular por una vía dónde los carriles no están delimitados, sólo circularemos por el carril derecho, pudiendo utilizar el resto cuando las circunstancias lo aconsejen.", preguntaId = 58))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Si el vehículo de detrás se acerca demasiado, es conveniente..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Mantener la misma separación con el vehículo de delante", esCorrecta = false, preguntaId = 59))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Disminuir la separación con el vehículo de delante", esCorrecta = false, preguntaId = 59))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Aumentar la separación con el vehículo de delante", esCorrecta = true, preguntaId = 59))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Aumentar la distancia de seguridad frontal al menos un segundo más, para poder actuar sin brusquedad.", preguntaId = 59))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Cuando llueve o hay viento, ¿por qué hay que tener más precaución con los ciclistas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Porque pueden salpicar agua", esCorrecta = false, preguntaId = 60))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Porque tienen más probabilidad de caerse", esCorrecta = true, preguntaId = 60))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Porque suelen estorbar el tráfico", esCorrecta = false, preguntaId = 60))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El viento y la lluvia pueden representar un grave peligro para los vehículos de dos ruedas, sobre todo para los ciclistas.", preguntaId = 60))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Entre la puesta y la salida del sol, ¿está permitido conducir una motocicleta que arrastra un remolque?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, si se hace a una velocidad un 10 por ciento por debajo de la genérica de la vía", esCorrecta = false, preguntaId = 61))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, como a cualquier otra hora del día", esCorrecta = false, preguntaId = 61))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 61))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las motocicletas podrán arrastrar un remolque o semirremolque, siempre que no superen el 50% de la masa en vacío del vehículo tractor y circulen de día y en condiciones que no disminuyan la visibilidad.", preguntaId = 61))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En condiciones meteorológicas que disminuyan sensiblemente la visibilidad..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Es obligatorio utilizar el sistema de alumbrado", esCorrecta = true, preguntaId = 62))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Solamente es obligatorio utilizar la luz antiniebla trasera", esCorrecta = false, preguntaId = 62))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No es obligatorio el uso del alumbrado, salvo que la señalización indique otra cosa", esCorrecta = false, preguntaId = 62))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Todos los vehículos que circulen entre el ocaso y la salida del sol o a cualquier hora del día en los túneles, pasos inferiores y tramos de vía afectados por la señal \"túnel\" o a cualquier hora del día cuando existan condiciones meteorológicas o ambientales que disminuyan sensiblemente la visibilidad, deberán llevar encendido el alumbrado que corresponda.", preguntaId = 62))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Circular por debajo del límite máximo de velocidad, ¿puede causar accidentes?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 63))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, cuando la velocidad no se adapte a las circunstancias del tráfico", esCorrecta = true, preguntaId = 63))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, sólo se pueden causar accidentes circulando por encima de ese límite", esCorrecta = false, preguntaId = 63))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Cuando circulamos a una velocidad que no se adapta a las condiciones climatológicas o a las circunstancias de la vía, del tráfico, del vehículo o a las condiciones del conductor, estaremos circulando a una velocidad inadecuada.", preguntaId = 63))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La conducción bajo los efectos del alcohol o de las drogas, ¿está considerada delito en el código penal?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 64))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, las sanciones son exclusivamente económicas", esCorrecta = false, preguntaId = 64))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "La conducción bajo los efectos del alcohol no, la conducción bajo los efectos de las drogas sí", esCorrecta = false, preguntaId = 64))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Conducir un vehículo de motor o un ciclomotor bajo la influencia de drogas tóxicas, estupefacientes, sustancias psicotrópicas o de bebidas alcohólicas, podrá será castigado con una pena de prisión de 3 a 6 meses o multa de 6 a 12 meses", preguntaId = 64))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un peatón que empuja un vehículo de dos ruedas, ¿por dónde está obligado a circular?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por la derecha, por la calzada o el arcén, según su sentido de la marcha", esCorrecta = true, preguntaId = 65))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por la izquierda, por la calzada o el arcén, según su sentido de la marcha", esCorrecta = false, preguntaId = 65))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Por la derecha o por la izquierda indistintamente", esCorrecta = false, preguntaId = 65))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las personas que empujan a pie un vehículo de dos ruedas que no sea un ciclo ni un ciclomotor, no son consideradas peatones, por lo tanto deberán circular por la derecha de la calzada o el arcén lo más cerca posible de su borde derecho.", preguntaId = 65))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Fumar mientras conduce, ¿qué efecto puede producir en la conducción?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Disminuye la capacidad de concentración", esCorrecta = true, preguntaId = 66))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Aumenta la agresividad", esCorrecta = false, preguntaId = 66))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Provoca una mayor resistencia a la fatiga", esCorrecta = false, preguntaId = 66))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Fumar es perjudicial para la salud y además puede afectar a la conducción, ya que suele provocar distracciones, como por ejemplo al encender un cigarrillo, disminuyendo nuestra capacidad de concentración.", preguntaId = 66))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Para prevenir la fatiga debe parar a descansar 20 ó 30 minutos..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cada 2 horas o 200 kilómetros de conducción continuada", esCorrecta = true, preguntaId = 67))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cada 4 horas o 400 kilómetros de conducción continuada", esCorrecta = false, preguntaId = 67))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "A mitad de recorrido", esCorrecta = false, preguntaId = 67))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Si nos encontramos cansados o con sueño mientras conducimos, lo más aconsejable es parar a descansar en un lugar adecuado y dormir unos 20 o 30 minutos.", preguntaId = 67))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Está prohibido conducir..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Más de una hora seguida sin descansar, pero sólo en vía urbana", esCorrecta = false, preguntaId = 68))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Más de una hora seguida sin descansar", esCorrecta = false, preguntaId = 68))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Utilizando cascos o auriculares conectados a aparatos receptores o reproductores de sonido", esCorrecta = true, preguntaId = 68))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Está prohibido conducir utilizando cascos o auriculares conectados a aparatos receptores o reproductores de sonido, dispositivos de telefonía móvil y cualquier otro medio o sistema de comunicación.", preguntaId = 68))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un agente con el brazo levantado verticalmente obliga a los vehículos que se aproximan de frente a ..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse", esCorrecta = true, preguntaId = 69))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Reducir la velocidad", esCorrecta = false, preguntaId = 69))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Continuar la marcha", esCorrecta = false, preguntaId = 69))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Cuando un agente levanta el brazo verticalmente obliga a detenerse a todos los usuarios de la vía que se acerquen al agente, salvo a los conductores que no lo puedan hacer en condiciones de seguridad suficientes.", preguntaId = 69))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿En qué situaciones tienen más dificultades las personas mayores?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En situaciones complejas de incorporaciones y salidas de vías donde se circula a alta velocidad", esCorrecta = true, preguntaId = 70))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En las maniobras de estacionamiento", esCorrecta = false, preguntaId = 70))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En los giros a la izquierda", esCorrecta = false, preguntaId = 70))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Tienen más dificultades para conducir en situaciones complejas que requieran una actuación rápida, como puede ser en las incorporaciones y salidas de vías donde se circula a alta velocidad.", preguntaId = 70))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Puede parar en un carril bus?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = true, preguntaId = 71))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, cuando sea por un tiempo inferior a 2 minutos", esCorrecta = false, preguntaId = 71))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, si utiliza la señal de emergencia", esCorrecta = false, preguntaId = 71))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En el carril bus se prohíbe su utilización a los conductores que no sean de transporte colectivo a utilizar dicho carril. La mención taxi también autoriza a ellos a poder utilizarlo.", preguntaId = 71))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "La probabilidad de que un accidente sea mortal es mayor cuando se circula a velocidad..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Inadecuada", esCorrecta = true, preguntaId = 72))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Adecuada", esCorrecta = false, preguntaId = 72))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Moderada", esCorrecta = false, preguntaId = 72))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Cuando circulamos a una velocidad que no se adapta a las condiciones climatológicas o a las circunstancias de la vía, del tráfico, del vehículo o a las condiciones del conductor, estaremos circulando a una velocidad inadecuada.", preguntaId = 72))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Al salir de un garaje, ¿qué debe hacer?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Moderar la velocidad por si hay peatones cruzando porque tienen prioridad", esCorrecta = true, preguntaId = 73))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Aumentar la velocidad para salir lo antes posible", esCorrecta = false, preguntaId = 73))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse siempre a la salida", esCorrecta = false, preguntaId = 73))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "La incorporación, cuando se efectúa desde el interior de un inmueble, debe hacerse extremando la precaución y por los lugares destinados a ello.", preguntaId = 73))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Dos vehículos del mismo tipo se encuentran en un estrechamiento y no se sabe cuál tiene preferencia, ¿cuál de ellos tiene prioridad?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El vehículo que tenga que dar marcha atrás una menor distancia.", esCorrecta = false, preguntaId = 74))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El vehículo que tenga que dar marcha atrás mayor distancia", esCorrecta = true, preguntaId = 74))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "El vehículo que tenga mayor anchura o longitud", esCorrecta = false, preguntaId = 74))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En un tramo de vía muy estrecho, en el que no exista señalización de prioridad, tendrá preferencia de paso el que vehículo que haya entrado primero.", preguntaId = 74))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Entre otros, ¿qué sistemas ADAS están permitidos en las pruebas de control de aptitudes y comportamiento para la obtención del permiso de conducción?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "\"EBD o Aviso de frenada de emergencia\" y \"LDW o Aviso de cambio involuntario de carril\"", esCorrecta = false, preguntaId = 75))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "\"ISA o Control de velocidad adaptativo\" y \"RCTA o Alerta de tráfico cruzado\"", esCorrecta = false, preguntaId = 75))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "\"AEBS o Sistema de frenado de emergencia\" y \"Hill Holder o Sistema de salida en pendiente\"", esCorrecta = true, preguntaId = 75))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Start-stop, Hill Holder, alumbrado automático, AEBS, cámara de marcha atrás, sensores de aparcamiento, EBD y sistema de detección de fatiga.", preguntaId = 75))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Conducir, con un permiso de la clase B, un turismo que arrastra un remolque ligero, ¿está permitido?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, en cualquier caso", esCorrecta = true, preguntaId = 76))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sólo si la masa máxima autorizada del conjunto no supera los 3.500 kilogramos", esCorrecta = false, preguntaId = 76))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, en ningún caso", esCorrecta = false, preguntaId = 76))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El permiso de la clase B autoriza a conducir automóviles cuya masa máxima autorizada no exceda de 3.500 kilogramos y cuyo número de asientos, incluido el del conductor, no exceda de 9.", preguntaId = 76))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Puede el conductor reducir la probabilidad de accidente debida al \"factor vehículo\"?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, los fallos mecánicos son impredecibles", esCorrecta = false, preguntaId = 77))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, mediante un mantenimiento adecuado del vehículo", esCorrecta = true, preguntaId = 77))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, si el vehículo no lleva los modernos sistemas de seguridad", esCorrecta = false, preguntaId = 77))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El estado de conservación y mantenimiento de los elementos esenciales del vehículo como los frenos, la dirección, suspensión, neumáticos o luces, es fundamental para la seguridad y prevención de accidentes.", preguntaId = 77))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Podemos emplear un dispositivo de preseñalización de peligro para advertir la presencia de un turismo averiado en la calzada?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No", esCorrecta = false, preguntaId = 78))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí", esCorrecta = true, preguntaId = 78))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sólo si la visibilidad es insuficiente", esCorrecta = false, preguntaId = 78))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Están obligados a llevar un dispositivo portátil de preseñalización de peligro todos los vehículos de motor excepto las motocicletas y los vehículos de tres ruedas.", preguntaId = 78))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuándo está permitido utilizar las señales acústicas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando circulo por vías urbanas solamente", esCorrecta = false, preguntaId = 79))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando circulo por cualquier vía", esCorrecta = false, preguntaId = 79))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando quiero adelantar fuera de poblado", esCorrecta = true, preguntaId = 79))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Las advertencias acústicas sólo se podrán realizar excepcionalmente para evitar un posible accidente, especialmente en vías estrechas con muchas curvas, para advertir fuera de poblado el propósito de adelantar.", preguntaId = 79))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En un paso a nivel, ¿qué debe hacer si la barrera está subiendo?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Pasar cuando lo hagan el resto de vehículos, se mueva o no la barrera", esCorrecta = false, preguntaId = 80))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Pasar cuando, por la altura, la barrera lo permita", esCorrecta = false, preguntaId = 80))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detenerse detrás de los demás vehículos, hasta que la barrera suba totalmente y permita el paso", esCorrecta = true, preguntaId = 80))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Al llegar a un paso a nivel o a un puente móvil que se encuentre cerrado o con la barrera o semibarrera en movimiento, los conductores y usuarios deberán detenerse uno detrás de otro en el carril correspondiente hasta que tengan paso libre.", preguntaId = 80))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cómo debe inmovilizar los vehículos accidentados?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Con el freno de mano y cortando el contacto", esCorrecta = true, preguntaId = 81))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Con unos calzos o cualquier elemento que sirva como tal", esCorrecta = false, preguntaId = 81))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Quitando el contacto de la batería", esCorrecta = false, preguntaId = 81))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Procuraremos inmovilizar los vehículos accidentados en un lugar seguro, con el freno de mano accionado y el motor parado.", preguntaId = 81))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Además de la señalización luminosa correspondiente, la marcha hacia atrás está permitido señalizarla con el brazo..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Moviéndolo de arriba abajo", esCorrecta = false, preguntaId = 82))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Extendido horizontalmente con la palma de la mano hacia atrás", esCorrecta = true, preguntaId = 82))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Doblado hacia arriba, con la mano extendida", esCorrecta = false, preguntaId = 82))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Si no disponemos de la luz de marcha atrás, la señalizaremos con el brazo izquierdo extendido con la palma de la mano hacia atrás.", preguntaId = 82))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Los vehículos especiales que circulan por una vía de uso público deben utilizar la luz rotativa amarillo auto cuando circulen a una velocidad..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No superior a 40 km/h", esCorrecta = true, preguntaId = 83))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No superior a 40 km/h, solamente de noche", esCorrecta = false, preguntaId = 83))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Superior a 40 km/h", esCorrecta = false, preguntaId = 83))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Los vehículos especiales o en régimen de transporte especial, entre otros, deberán utilizar una luz rotativa amarillo-auto, visible desde todas las direcciones a 100 m de distancia, tanto día como de noche.", preguntaId = 83))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "En un turismo, ¿dónde debe colocar la placa \"L\" un conductor novel?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En un lugar visible en la parte posterior derecha", esCorrecta = false, preguntaId = 84))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En un lugar visible en la parte posterior izquierda", esCorrecta = true, preguntaId = 84))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En cualquier lugar visible de la parte posterior", esCorrecta = false, preguntaId = 84))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "En motocicletas y vehículos de 3 ruedas será suficiente con que vaya colocada en un sitio visible de la parte posterior.", preguntaId = 84))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un conductor necesita hacer una llamada urgente por el móvil, ¿qué debe hacer?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Buscar un lugar seguro donde detener el vehículo para hacer la llamada", esCorrecta = true, preguntaId = 85))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Disminuir la velocidad para poder hablar sin peligro", esCorrecta = false, preguntaId = 85))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Detener el vehículo en cualquier lugar para hacer la llamada", esCorrecta = false, preguntaId = 85))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Se prohíbe la utilización durante la conducción de dispositivos de telefonía móvil y cualquier otro medio o sistema de comunicación.", preguntaId = 85))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuándo debe desactivar el airbag frontal de un asiento?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "En ningún caso", esCorrecta = false, preguntaId = 86))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando en ese asiento viaje una mujer embarazada", esCorrecta = false, preguntaId = 86))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cuando en ese asiento instale un dispositivo de retención para niños orientado hacia atrás", esCorrecta = true, preguntaId = 86))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El airbag es un sistema de seguridad pasiva muy seguro pero, para evitar efectos adversos, debemos desactivarlo al utilizar un dispositivo de retención para niños orientado hacia atrás.", preguntaId = 86))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "Un botiquín de primeros auxilios, ¿se encuentra entre la dotación obligatoria de los vehículos de más de nueve plazas?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "No, un botiquín es solamente recomendable", esCorrecta = true, preguntaId = 87))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Es obligatorio dependiendo del número de pasajeros transportados", esCorrecta = false, preguntaId = 87))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sí, es obligatorio", esCorrecta = false, preguntaId = 87))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Pese a no ser obligatorio, siempre es recomendable llevar un pequeño botiquín en nuestro vehículo con todos aquellos productos necesarios para realizar curas en caso de accidente.", preguntaId = 87))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "El permiso de circulación es obligatorio para los remolques y semirremolques..."))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Que tengan una MMA no superior a 750 kg", esCorrecta = false, preguntaId = 88))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Cualquiera que sea su MMA", esCorrecta = false, preguntaId = 88))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Que tengan una MMA superior a 750 kg", esCorrecta = true, preguntaId = 88))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "Todos los vehículos de motor, y remolques y semirremolques de más de 750 kilogramos deberá tener su propio permiso de circulación de forma obligatoria.", preguntaId = 88))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Cuántos chalecos reflectantes debe llevar obligatoriamente en un turismo?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Dos", esCorrecta = false, preguntaId = 89))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Uno, aunque es recomendable llevar dos", esCorrecta = true, preguntaId = 89))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Ninguno, ya que no es obligatorio", esCorrecta = false, preguntaId = 89))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "El Reglamento General de Vehículos establecerá la obligación de llevar en el vehículo dos triángulos de preseñalización del peligro y al menos un chaleco reflectante de alta visibilidad siendo recomendable que llevemos dos.", preguntaId = 89))

                App.getDb().preguntasDao()
                    .save(Preguntas(descripcion = "¿Qué es el ABS?"))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sistema de control de seguridad", esCorrecta = false, preguntaId = 90))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sistema de frenado antibloqueo", esCorrecta = true, preguntaId = 90))
                App.getDb().respuestasDao()
                    .save(Respuestas(descripcion = "Sistema de cierre centralizado", esCorrecta = false, preguntaId = 90))
                App.getDb().explicacionDao()
                    .save(Explicacion(descripcion = "ABS son las siglas de «Anti-lock Braking System», en español «Sistema Antibloqueo de Frenos» o «Antiblockiersystem», en alemán.", preguntaId = 90))
            }
        }
    }
}